version: '3.8'

services:
  db-mysql:
    image: mysql:latest
    restart: always
    environment:
#      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: reservas
      MYSQL_USER: admin
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: